### ISSUE TITLE
Crashes on Windows XP for no apart reason

### ISSUE THREAD

**Issue by adlogic** [Sinflower/Translation-Aggregator#1]
I used latest release.

**Comment by Sinflower** [comment]
Generally, Windows XP is not actively supported and I currently do not have an XP system to debug the crash. Also please provide a bit more information regarding the crash

- when does it happen (directly at startup or after a constant/random amount of time)
- does it happen only for certain translators

**Comment by adlogic** [comment]
Yes, but I am not sure this is really related to WinXP. Anyway I can do a testing if this helps.

After you try to translate using Google Translate it crashes.

**Comment by Sinflower** [comment]
Please try this version and tell me whether or not it crashes as well.

[Translation Aggregator.zip](https://github.com/Sinflower/Translation-Aggregator/files/2419923/Translation.Aggregator.zip)

**Comment by adlogic** [comment]
Same crash. I checked windows events, this is what address that crash occured:

Application Failure  translation aggregator.exe  0.0.0.0 
in translation aggregator.exe 0.0.0.0 at offset 000235c0

If I counted offsets correctly, then this is in TryMakeRequest() so most likely it is as you guessed related to connection issue.

**Comment by Sinflower** [comment]
I finally had some time to look into this.
Could you give this version a try?
The crash should be fixed and Google should translate properly.
[Translation Aggregator.zip](https://github.com/Sinflower/Translation-Aggregator/files/2452791/Translation.Aggregator.zip)

**Comment by adlogic** [comment]
All works now, thanks! Will try to do more tests, but it seems all is okay.
