### ISSUE TITLE
I have a strange issue with TA

### ISSUE THREAD

**Issue by Pixiedust2** [Sinflower/Translation-Aggregator#11]
Im having this kind of a bug, dont know for sure, but TA translation is normal, then sometimes when i click to read the next sentence it freeze for 5/6 seconds on the previous line, then the next line appears on Jparser. Strange thing is that just happens while using Google. I tried with Bing and didn't freeze, every sentence appeared normally.
Anyone having the same problem or is just me?
Any help?

**Comment by FabioManoel1977** [comment]
Yeah it always happened tô me too. Happens every five minutes and freeze translator aggregator long 5 secounds. I never complained because i was thinking that it happens tô me only

**Comment by Pixiedust2** [comment]
Me too. I hope this problem can be solved. I like Google translation better. Bing is good too, but sometimes it's weird.

**Comment by Sinflower** [comment]
See if this fixes the error and if google still works properly.
[Translation Aggregator.zip](https://github.com/Sinflower/Translation-Aggregator/files/3586649/Translation.Aggregator.zip)

**Comment by Pixiedust2** [comment]
I tested and now works properly without freezing. Thanks for fixing it. I really apreciate it.
