### ISSUE TITLE
Characters cutting google translation

### ISSUE THREAD

**Issue by Ileca** [Sinflower/Translation-Aggregator#12]
Example:

> 【玲二】「ちゃんと入れてる？　確認しないとな」
> [Reiji] “Is it properly?
> 【玲二】「怖じ気付いちゃったかぁー……西田も可哀想に。好きな子と俺のキス写を見るハメになるな」
> [Koji] “I'm scared ... Nishida feels sorry. Don't be addicted to seeing my kiss with my favorite child.”

but if I replace the dot with a ?

> 【玲二】「怖じ気付いちゃったかぁー……西田も可哀想に？好きな子と俺のキス写を見るハメになるな」
> [Shinji] "Did you realize that you're scared ... Nishida is too sad?

**Comment by Sinflower** [comment]
That is a problem on Googles side, the same cut off happens when you go to
https://translate.google.com
and enter your text, so nothing I can fix.

**Comment by Ileca** [comment]
Aouch. I tried a fresh install but I didn't check that because I didn't expect gogle to make such a mistake. It's not the first time it happened and I thought I remember you saying you fixed a similar issue but seems like I wasted your time.
Well, I reported it to them. Let's hope their robot army will hand it over to a human in less than a month.

**Comment by Ileca** [comment]
Ok, I am reopening because I found a real issue I checked against goggle.

【男】「いいじゃん、ブッチしても。俺たちが映画よりも楽し　いとこに連れてってあげるよ～」
TA > [Men] "It's okay, but even if I'm butt.
GT > [Men] "It's okay, even if I'm Butch. We're more fun than a movie, I'll take you to my cousin ~"

**Comment by Sinflower** [comment]
Yeah, it's really strange, but unfortunately, as long as Google does not properly fix this problem there is little I can do.
