### ISSUE TITLE
Google translation is weird

### ISSUE THREAD

**Issue by Pixiedust2** [Sinflower/Translation-Aggregator#15]
A few week ago i noticed the translation that Google is making is really weird. It doesn't make sense at all and some of the names of the characters appears in all caps like "TAKASHI".
I tried translating direct in the website and it was more accurate.
Is this a bug that can be fixed? Is anyone having the same issue or just me?

**Comment by Pixiedust2** [comment]
Here is a example:

![google1](https://user-images.githubusercontent.com/54959049/115574984-81b84d00-a298-11eb-9b73-1bd7ecabb2d9.png)
![google](https://user-images.githubusercontent.com/54959049/115574993-841aa700-a298-11eb-8c3e-09ecf7c89040.png)

There's a lot more worse translations than that.

**Comment by Zulshin** [comment]
I've been having same issue. .  Pretty sure its bugged and linking to a diffrent translator or somthing. the quality is awful though. Hope a fix is found.

**Comment by Sinflower** [comment]
The API of the web-based google translation was changed, once I have a bit more time at hand I will fix this problem by implementing the new version.

**Comment by Pixiedust2** [comment]
Great! Take your time. Thank you for still work on this.

**Comment by Sinflower** [comment]
Sorry for the long silence; I just published a new release that utilizes the new google API. However, I still haven't managed to break their new bot protection. Therefore, TAs translation quality will be significantly lower compared to the website.

**Comment by Pixiedust2** [comment]
No problem. Yeah, the translation still bad as you said. I saw that you fixed Bing though, so i'll stick with it for now. Thank you very much.
