### ISSUE TITLE
Bing not working on r194

### ISSUE THREAD

**Issue by 7777ale7777** [Sinflower/Translation-Aggregator#16]
I've been using this version for over a year and there's never been a problem with Bing that lasted more than a day, but now it seems that is not working anymore. I keep getting this error: 

Unrecognized response received 
{"statusCode":400,"errorMessage":""}

It was working just fine last month when I last used it, but I've been trying since last week and is not working, at least for me. Am I the only one with this problem?

**Comment by Sinflower** [comment]
Hi, sorry for the late response, I just published a new release that fixes the Bing error.

**Comment by 7777ale7777** [comment]
It works! Thank you for continuing to work on this!
