### ISSUE TITLE
DeepL doesn't work

### ISSUE THREAD

**Issue by nisehime** [Sinflower/Translation-Aggregator#17]
I know DeepL is experimental but it plainly doesn't work. Not sure what additional info to bring, I just click translate, it shows "requesting data" for one second and just nothing then.

**Comment by Sinflower** [comment]
I also encountered that problem a few times during development but as it vanished after a while I thought it might just be a short term problem on their side. I will look into it.

**Comment by Sinflower** [comment]
I uploaded a new release that should fix the Deepl problem, if it still persists please let me know.

**Comment by nisehime** [comment]
Thank you. So far, it works, but only English translation. Could you also add support for British English in DeepL please? For some reason, sometimes it works better than American one and vice versa, so would be nice if you could quickly switch between them or something.

**Comment by mspykerez** [comment]
For those interested, there is a great FREE DeepL alternative that works offline with no limitations.
https://www.reddit.com/r/visualnovels/comments/qnsgd2/from_sugoi_translator_developer_today_i_will_send/
I think you can use the clipboard along to salvage some of the Translation Aggregator features.
