### ISSUE TITLE
Google translate bug

### ISSUE THREAD

**Issue by Plopbyte** [Sinflower/Translation-Aggregator#18]
Only the first line is translated. Is it just me or happening to everyone else? 
Also thanks for still updating this @Sinflower 

Example text:
![google bug](https://user-images.githubusercontent.com/62284471/136466779-55d55c61-6e74-4fd9-a50b-501e914de458.JPG)

Edit: Bing after sometime will also show this error:
Unrecognized response received:

{"ShowCaptcha":true}

**Comment by Sinflower** [comment]
Hi,
please try the attached testing version, it should fix the problem.
As for Bing, yes after a while Bing tends to autoban people I have not figured out how to fix that yet.

[Translation Aggregator.zip](https://github.com/Sinflower/Translation-Aggregator/files/7307368/Translation.Aggregator.zip)

**Comment by Plopbyte** [comment]
Thank you for the fast response, google seems to be working now. Truly life saver since I only use web translator. 
Hope Bing can also be fixed, Bing translation is very good (along with Google).  Thanks once again for keeping TA alive!
