### ISSUE TITLE
Translation substitutions not working

### ISSUE THREAD

**Issue by Fealow** [Sinflower/Translation-Aggregator#2]
I've tried googling this to see if anyone else has had the issue, but I can not seem to find anything relating to it. No matter what I try I can't get any substitutions working when the option to have them enabled is checked in the drop down menu. Is there any chance you could test this on your end and let me know if it's working or not please?

I'm using the latest version of TR.

Thanks.

**Comment by Sinflower** [comment]
I just tested it and it worked fine for me, see example below:

![image](https://user-images.githubusercontent.com/23295734/53569992-b0798380-3b65-11e9-9719-f83c30e06047.png)
![image](https://user-images.githubusercontent.com/23295734/53570141-136b1a80-3b66-11e9-8df4-0305000d2379.png)
