### ISSUE TITLE
Text is not copied into the program 

### ISSUE THREAD

**Issue by allebar** [Sinflower/Translation-Aggregator#21]
Text is not automatically inserted into the program, so you have to do everything manually. Is it possible to fix this? I enabled the automatic translation option, if anything.

**Comment by Sinflower** [comment]
Hmm, I did a quick test, and the text was copied automatically into the program without any problem.
Can you give me an example of the text you are trying to translate?
Also, do you copy the text manually to the clipboard or is it inserted by a text hock like Textractor or ITHVNR?
