### ISSUE TITLE
DeepL doesn't work again

### ISSUE THREAD

**Issue by Quizzle01** [Sinflower/Translation-Aggregator#22]
Hello! I have a problem with Deepl again. It stops translating after a few phrases and then shows empty window. Maybe there is an opportunity to fix it somehow? Thank you in advance.

**Comment by Sinflower** [comment]
Hi,
I think I managed to fix the problem, please test this version and tell me if it fixes the problem.

[Translation Aggregator.zip](https://github.com/Sinflower/Translation-Aggregator/files/9729122/Translation.Aggregator.zip)

**Comment by Quizzle01** [comment]
Hi! It works perfectly now! Thank you very much!
