### ISSUE TITLE
Bing not working

### ISSUE THREAD

**Issue by Plopbyte** [Sinflower/Translation-Aggregator#25]
Bing always gives this response:

Unrecognized response received:

{"statusCode":205,"errorMessage":""}

I remember I use it last december and Bing still worked.
@Sinflower Please fix it if you have the time. Thanks!

**Comment by Sinflower** [comment]
Hi,
please try this version and tell me if it fixes the problem.
[Translation Aggregator.zip](https://github.com/Sinflower/Translation-Aggregator/files/10830192/Translation.Aggregator.zip)

**Comment by DemonKiller1991** [comment]
Bing is working now, but Baidu stopped with this error.

Unrecognized response received:

{"errno":1022,"errmsg":"\u8bbf\u95ee\u51fa\u73b0\u5f02\u5e38\uff0c\u8bf7\u5237\u65b0\u540e\u91cd\u8bd5\uff01","error":1022,"errShowMsg":"\u8bbf\u95ee\u51fa\u73b0\u5f02\u5e38\uff0c\u8bf7\u5237\u65b0\u540e\u91cd\u8bd5\uff01"}

**Comment by Sinflower** [comment]
Try this version it should also "fix" Baidu. However, it looks like Baidu implemented a form of request speed limit (that's what the error message tells you), meaning you have to wait a few seconds between requests, which can be reproduced using the website. The new version now catches this error and prints a different error message telling you to retry in a few seconds.
[Translation Aggregator.zip](https://github.com/Sinflower/Translation-Aggregator/files/10831670/Translation.Aggregator.zip)
