### ISSUE TITLE
Antivirus Scanners flag the exe file as a Trojan

### ISSUE THREAD

**Issue by DemonKiller1991** [Sinflower/Translation-Aggregator#26]
Could you also look into the issue about antivirus flagging the exe as a Trojan. (McAffee, Norton, AVG, Microsoft Defender)

**Comment by Sinflower** [comment]
I have actually been looking into this for quite a while now. Unfortunately, there is not much I can do about this, as it is a heuristic error from the AVs, which is not uncommon, especially considering the type of operations TA performs. I currently got it down to 11 hits ... but unfortunately, Microsoft is still one of them.

https://www.virustotal.com/gui/file/1d237685063f901932b182d2fb72cbb4f7716a04b66939699e46ade6339e418c?nocache=1

**Comment by Sinflower** [comment]
I actually managed to find a build configuration where I don't get any false positives from Microsoft. I will probably use that setup for the next release.

https://www.virustotal.com/gui/file/8e60138b713a58e9a5724eafdc5e2990f65db62989e0bacbaba4680f5ee7320a?nocache=1
