### ISSUE TITLE
You forget to compile Unofficial Release r199 version in download section

### ISSUE THREAD

**Issue by fhc2** [Sinflower/Translation-Aggregator#27]
Thank you very much,  Sinflower, for still updating this application, I guess you are currently the unique person that cares about us that cannot learn Japanese and still insisting in play hentai games in japanese, but,  You forget to compile Unofficial Release r199 version in download section only have the Assets, no exe file.

**Comment by Sinflower** [comment]
Thank you for the info. I was really certain that I added the attachment ..., anyway, it should now be present :-) .
