### ISSUE TITLE
Google translate is blocked after a while

### ISSUE THREAD

**Issue by nagicle** [Sinflower/Translation-Aggregator#3]
I'm getting blocked by google. (Unregcognized respond received...) This was fixed in the latest version (r190), but the blocking seems to be back. 

Thanks

**Comment by Sinflower** [comment]
Google changed (fixed) their anti-abuse system if you send to many requests in a certain time window you will be blocked. Unfortunately, there is nothing I can do about it.

**Comment by nagicle** [comment]
I see. Thanks for the reply and for keeping TA alive. Fortunately, other translator are still working fine-- Bing, Yandex, Excite, etc.
