### ISSUE TITLE
Systran not working anymore

### ISSUE THREAD

**Issue by crowns741** [Sinflower/Translation-Aggregator#5]
Systran is not working after site updated.

**Comment by FabioManoel1977** [comment]
Not really a big deal, Systran translation is SO BAD If compared to Google, Bing and Yandex...

**Comment by crowns741** [comment]
Systran Translation is the best one to MTL from chinese.
Could you please update this ? I'm using the same for years, thanks.
I'll try the aforementioned ones too.

**Comment by FabioManoel1977** [comment]
I am sorry, I not know that you are talking about chinese language. I was thinking tat you are talking about english language.

**Comment by Sinflower** [comment]
Sorry for the late response, I am currently working on fixing Systrans.

**Comment by Sinflower** [comment]
I think I managed to fix SysTran, the attached file is a pre-release version of the fix, please test it a bit and see if it works as expected and does not cause any errors.

[Translation Aggregator.zip](https://github.com/Sinflower/Translation-Aggregator/files/3511314/Translation.Aggregator.zip)

**Comment by crowns741** [comment]
Thanks for trying to solve the issue, but it is still not working.

**Comment by Sinflower** [comment]
Windows 7 or 10?
And what error message do you get?

**Comment by crowns741** [comment]
Windows 7, "Connection Error".

**Comment by Sinflower** [comment]
There appears to be some problem on Windows 7 that prevents SysTran to work properly in TA, because I also get a Connection Error on my Windows 7 machine, while it works without a problem on my Windows 10 systems.

**Comment by limitlessheart** [comment]
r194 for systran is working. thanks Sinflower

**Comment by crowns741** [comment]
> 
> 
> r194 for systran is working. thanks Sinflower

Are you using Windows 10 too ?

**Comment by limitlessheart** [comment]
no, i use windows 8.1
