### ISSUE TITLE
Bing translator no longer working

### ISSUE THREAD

**Issue by iraiken** [Sinflower/Translation-Aggregator#6]
Bing is returning an unrecognized response received error for me as of 2 days ago, possible url/format change?

**Comment by FabioManoel1977** [comment]
Same thing also is happening with Yandex

Please, fix Bing and Yandex, I beg you, Sinflower

**Comment by Sinflower** [comment]
For Bing please test the new release r192.
As for Yandex, it appears that they now start requesting captcha when they notice unusual behavior which results in TA not being able to get a valid session id from the site and therefore not working. 
I will see if I can find a workaround but for now, you might want to refrain from using yandex.
