### ISSUE TITLE
Google no working today

### ISSUE THREAD

**Issue by FabioManoel1977** [Sinflower/Translation-Aggregator#7]
is not working for me google, Bing and Yandex.

Please,Sinflower I beg you fix it. I cannot play my hentai games without it.

See error message:

Unrecognized response received:

<!DOCTYPE html><html lang=en><meta charset=utf-8><meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width"><title>Error 403 (Forbidden)!!1</title><style nonce="NGP2d2FqNxwMPgz22FiqCA">*{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{color:#222;text-align:unset;margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px;}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}pre{white-space:pre-wrap;}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}</style><div id="af-error-container"><a href=//www.google.com><span id=logo aria-label=Google></span></a><p><b>403.</b> <ins>That’s an error.</ins><p>We're sorry, but you do not have access to this page. <ins>That’s all we know.</ins></div>

**Comment by Sinflower** [comment]
Please try the new release, it should fix Bing and Google problems.
As for Yandex, please look at [this](https://github.com/Sinflower/Translation-Aggregator/issues/6#issuecomment-511540507) answer where I explained why it's currently not working properly.

**Comment by FabioManoel1977** [comment]
Bing is working, then I can play my games again, thank you very much, Sinflower, I love you.

Too bad google is not working anymore, but, is is no big deal anymore, If Bing works, I am satisfied only with this 

I guess is the same error message:

Unrecognized response received:

<!DOCTYPE html><html lang=en><meta charset=utf-8><meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width"><title>Error 403 (Forbidden)!!1</title><style nonce="17KdhTmJJ2auPd6vh0lHeA">*{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{color:#222;text-align:unset;margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px;}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}pre{white-space:pre-wrap;}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}</style><div id="af-error-container"><a href=//www.google.com><span id=logo aria-label=Google></span></a><p><b>403.</b> <ins>That’s an error.</ins><p>We're sorry, but you do not have access to this page. <ins>That’s all we know.</ins></div>

**Comment by Ileca** [comment]
Well, I don't know why but google is really capricious. I have this 403 error 3/4 of the time and r192 didn't fix this.

**Comment by FabioManoel1977** [comment]
> 
> 
> Well, I don't know why but google is really capricious. I have this 403 error 3/4 of the time and r192 didn't fix this.

is not just you. same thing happens to me too.

**Comment by Sinflower** [comment]
Please try the newest release, it hopefully fixes the google problem.

**Comment by FabioManoel1977** [comment]
Sinflower , thank you very much, I love you you are a King Among Men. It is working perfect fine, at least for the time being. I hope google not change something again and stop works.
