### ISSUE TITLE
Google not working again

### ISSUE THREAD

**Issue by Wolfpup67** [Sinflower/Translation-Aggregator#8]
I'm using the newest version and I'm getting the 403 error showing again.

Unrecognized response received:

<!DOCTYPE html><html lang=en><meta charset=utf-8><meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width"><title>Error 403 (Forbidden)!!1</title><style nonce="LUU+k2NeHt5jDsV4770rFQ">*{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{color:#222;text-align:unset;margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px;}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}pre{white-space:pre-wrap;}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}</style><div id="af-error-container"><a href=//www.google.com><span id=logo aria-label=Google></span></a><p><b>403.</b> <ins>That’s an error.</ins><p>We're sorry, but you do not have access to this page. <ins>That’s all we know.</ins></div>

**Comment by FabioManoel1977** [comment]
Me too...  also in the few times that works, is translated only the first part of the sentence, but, in 90% of time show the same error message.

I guess, is impossible to fix google. Does not matter how many times it is fixed, is always broken in one week...

**Comment by Theo422** [comment]
Google works with the R190 version, but it still has the one line bug that was fixed in a later update

**Comment by FabioManoel1977** [comment]
R190 is completely useless, the one line bug makes it useless.

**Comment by Sinflower** [comment]
Please try and see if [R192](https://github.com/Sinflower/Translation-Aggregator/releases/tag/r192) works consistently, I did a bit of testing and it looked like it works fine.

**Comment by FabioManoel1977** [comment]
Yeah, I tested it long 30 minutes and indeed R192 is working perfect fine, even yandex is working... This really is weird, 15 days ago R192 was not working, but today is working.... Lets see for so long it will keep working.... I will post here If I notice any change... But for sure is working 100% perfect in this moment.

**Comment by 10asd28** [comment]
I just downloaded r192 and Google always gets that error. I used 2016.03.16 r183 for the longest time until the recent Windows 10 update broke it.

**Comment by FabioManoel1977** [comment]
> 
> 
> I just downloaded r192 and Google always gets that error. I used 2016.03.16 r183 for the longest time until the recent Windows 10 update broke it.

I advice you to use uyjulian version then:

https://github.com/uyjulian/Translation-Aggregator/releases

uyjulian version have some kind of trick that avoid google bug on WIndows 10. Also Bing and Yandex works just fine. If show up any error, just close and open again the aplication.  Using Google, Bing and Yandex at same time you can get a almost 100% correctly translation, since each translator engine translate the same phrase in different ways.

**Comment by FabioManoel1977** [comment]
Too bad uyjulian version nowadays stopped works with google

**Comment by FabioManoel1977** [comment]
Today, 08-december-2020  uyjulian version stopped working with Google Translator, then I tried again after one year to use Sinflower version and it is working 100% fine. Google, Bing and Baidu working 100 fine with Sinflower version. I am usngo ling one hours without any trouble.

Thank you very much,  Sinflower  !!

![2020-12-08 21_08_40-](https://user-images.githubusercontent.com/41028393/101556447-a1aa3c80-3999-11eb-8691-f446673b57f2.jpg)
